### ISSUE TITLE
Constant false positive

### ISSUE THREAD

**Issue by ckegels** [thefipster/esphome-mmwave-sensors#6]
Lite module:
i am getting body movement readings even when nobody is present (presence alwayson)
i am using an esp8266 and for rx and tx i am using the hardware rx tx of the 8266 with log baud to 0
any ideas?

what might be intereseting is the following: when moving around the sensor the value of body movement drops between 0 and 12 and when no movement it jumps up to 100 than back down to 50

**Comment by Chrisrdouglas** [comment]
Do you have any kind of material in front of the sensor? that was my issue the other night. I had a 2 mm thick plastic cover in front of it and removing that cover helped with my issue. I then printed a new cover that was only .5 mm thick and i haven't had a problem since

additionally, what do you have your parity set to? I had to manually set mine to NONE like so

```yaml
uart:
  id: uart_bus
  baud_rate:  115200
  rx_pin: GPIO16
  tx_pin: GPIO17
  parity: NONE
```
